name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio principal
        uses: actions/checkout@v4

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs

      - name: Tangle README.org
        run: emacs --batch README.org -l org -f org-babel-tangle

      - name: Run Makefile
        run: make publica

      - name: Deploy docs/ a gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.NUEVO_TOKEN_CLASSIC_HASTA_JULIO_2026 }}
          publish_dir: ./docs
          publish_branch: gh-pages
